from youtube_transcript_api import YouTubeTranscriptApi

# retrieve video_id from input
video_id = input("Enter YouTube video ID (ie. lwOHQEf_66I) :  ")

# run youtube api and assign to a dictionary
scriptd = YouTubeTranscriptApi.get_transcript(video_id)

print("Auto-generated transcript for " + video_id + ":\n")

# get count
#count = (len(scriptd))

# parse dictionary data to readable text
for i in range(len(scriptd)):

    print(scriptd[i].get('text'), end = " ")

print("\n")

# additional example uses below
# retrieve the available transcripts
# transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

# iterate over all available transcripts
# for transcript in transcript_list:

    # the Transcript object provides metadata properties
    # print(
        # transcript.video_id,
        # transcript.language,
        # transcript.language_code,
        # whether it has been manually created or generated by YouTube
        # transcript.is_generated,
        # whether this transcript can be translated or not
        # transcript.is_translatable,
        # a list of languages the transcript can be translated to
        # transcript.translation_languages,
    # )

    # fetch the actual transcript data
    # print(transcript.fetch())

    # translating the transcript will return another transcript object
    # print(transcript.translate('en').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
# transcript = transcript_list.find_transcript(['de', 'en'])

# or just filter for manually created transcripts
# transcript = transcript_list.find_manually_created_transcript(['de', 'en'])

# or automatically generated ones
# transcript = transcript_list.find_generated_transcript(['de', 'en'])
